version: '3'
services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    expose:
      - "6379"
    volumes:
      - ./redis:/data
    networks:
      - ai-platform-network

  app:
    image: ghcr.io/${GHCR_USER}/chat-trying:latest
    container_name: ai-platform
    restart: always
    ports:
      - "8000:8094"
    depends_on:
      - redis
    links:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      REDIS_DB: 0
      SECRET: "change-this-to-a-random-secret-at-least-32-chars"
      SERVE_STATIC: "true"
      VOLCENGINE_API_KEY: "${VOLCENGINE_API_KEY}"
      DEEPSEEK_API_KEY: "${DEEPSEEK_API_KEY}"
      SERVER_PORT: "8094"
    volumes:
      - ./config:/config
      - ./logs:/logs
      - ./storage:/storage
      - ./db:/db
      - ./students.csv:/students.csv
    networks:
      - ai-platform-network

networks:
  ai-platform-network:
    driver: bridge
